name: Automatic Distribution

on:
  push:
    branches:
      - main

jobs:
  update-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: main
          filters: |
            index:
              - 'index.js'

      - uses: actions/setup-node@v4
        if: ${{ steps.filter.outputs.index == 'true' }}
      - uses: crazy-max/ghaction-import-gpg@v6
        if: ${{ steps.filter.outputs.index == 'true' }}
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      
      - uses: reecetech/version-increment@2024.4.4
        id: version
        if: ${{ steps.filter.outputs.index == 'true' }}
        with:
          scheme: calver

      - name: Add Node Modules and Push
        if: ${{ steps.filter.outputs.index == 'true' }}
        env:
          checkout_branch: v${{ steps.version.outputs.major-version }}.${{ steps.version.outputs.minor-version }}.x
          GH_TOKEN: ${{ github.token }}
        run: |
          git checkout ${{ env.checkout_branch }} 2>/dev/null || git checkout -b ${{ env.checkout_branch }}
          git merge -X theirs ${{ github.event.repository.default_branch }}
          npm install
          git add ./node_modules -f
          git commit -am "Push node modules"
          git tag ${{ steps.version.outputs.version }}
          git push -f --set-upstream origin ${{ env.checkout_branch }}
          git push origin tag ${{ steps.version.outputs.version }}
